"""
Preprocessing pipeline orchestration (Sections 11, 12, 13).

Chains every preprocessing stage into a single, configurable,
reproducible pipeline:

    Load Data -> Validate -> Handle Missing Values -> Remove Outliers ->
    Normalize -> Detrend -> Window Generation -> Statistics ->
    (Optional Augmentation) -> Save Processed Data

Each stage's execution time, sample count, warnings, and errors are
recorded in a :class:`StageLog`, and the whole run's configuration and
per-stage logs are written out as ``preprocessing_report.json`` alongside
the processed data (Section 12/13).

This module is purely additive — it does not alter
``src/data_pipeline.py`` or ``src/preprocessing.py``; it *composes* the
new Section 2-9 modules (``data_validation``, ``missing_values``,
``outlier_detection``, ``normalization``, ``detrending``, ``windowing``,
``feature_statistics``, ``augmentation``) into one orchestrated run.

Example
-------
>>> from src.preprocessing_pipeline import PreprocessingPipeline
>>> pipeline = PreprocessingPipeline()
>>> result = pipeline.run(time, flux, target_id="Kepler-10b", mission="Kepler")
>>> result.output_dir
'data/processed/Kepler-10b'
"""

from __future__ import annotations

import json
import logging
import os
import time as time_module
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional

import numpy as np

from src.augmentation import augment
from src.data_validation import ValidationReport, validate_lightcurve
from src.detrending import detrend
from src.feature_statistics import LightCurveStatistics, compute_statistics
from src.missing_values import handle_missing_values
from src.normalization import normalize
from src.outlier_detection import OutlierStats, remove_outliers
from src.preprocessing_config import PreprocessingConfig, load_preprocessing_config
from src.windowing import Window, generate_windows, windows_to_arrays

logger = logging.getLogger(__name__)

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@dataclass
class StageLog:
    """
    Execution record for a single pipeline stage (Section 13).

    Attributes
    ----------
    stage_name:
        Human-readable stage name, e.g. ``"validate"``.
    execution_time_sec:
        Wall-clock time the stage took to run.
    n_samples:
        Number of samples (flux points) present *after* this stage ran.
    warnings:
        Any warning strings generated by this stage.
    errors:
        Any error strings generated by this stage (stage did not
        necessarily abort — see ``PreprocessingPipeline.run`` docstring).
    config_used:
        Dict snapshot of the configuration parameters relevant to this
        stage, for reproducibility.
    """
    stage_name: str
    execution_time_sec: float
    n_samples: int
    warnings: List[str] = field(default_factory=list)
    errors: List[str] = field(default_factory=list)
    config_used: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class PipelineResult:
    """
    Full result of a preprocessing pipeline run.

    Attributes
    ----------
    target_id, mission:
        Identifiers for the processed target.
    time, flux:
        Final processed ``(time, flux)`` arrays (post validation, missing-
        value handling, outlier removal, normalization, and optional
        detrending — before windowing).
    windows:
        List of :class:`src.windowing.Window` objects, or ``None`` if
        windowing was skipped.
    validation_report:
        The :class:`src.data_validation.ValidationReport` from the
        Validate stage.
    outlier_stats:
        The :class:`src.outlier_detection.OutlierStats` from the Remove
        Outliers stage.
    normalization_params:
        Dict of fitted normalization parameters, for reproducibility.
    statistics:
        The :class:`src.feature_statistics.LightCurveStatistics` computed
        on the final processed light curve.
    stage_logs:
        Ordered list of :class:`StageLog` records, one per pipeline stage.
    output_dir:
        Directory the results were saved to, or ``None`` if saving was
        skipped.
    """
    target_id: str
    mission: str
    time: np.ndarray
    flux: np.ndarray
    windows: Optional[List[Window]]
    validation_report: ValidationReport
    outlier_stats: OutlierStats
    normalization_params: Dict[str, Any]
    statistics: LightCurveStatistics
    stage_logs: List[StageLog]
    output_dir: Optional[str]

    def to_report_dict(self) -> Dict[str, Any]:
        """Build the JSON-serializable ``preprocessing_report.json`` content."""
        return {
            "target_id": self.target_id,
            "mission": self.mission,
            "validation": self.validation_report.to_dict(),
            "outlier_stats": self.outlier_stats.to_dict(),
            "normalization_params": self.normalization_params,
            "statistics": self.statistics.to_dict(),
            "stages": [s.to_dict() for s in self.stage_logs],
            "n_windows": len(self.windows) if self.windows is not None else 0,
        }


class PreprocessingPipeline:
    """
    Orchestrates the full configurable preprocessing pipeline (Section 11).

    Parameters
    ----------
    config:
        A :class:`src.preprocessing_config.PreprocessingConfig`. If
        ``None``, loaded via
        :func:`src.preprocessing_config.load_preprocessing_config`.

    Notes
    -----
    Each stage is wrapped so that an exception in one stage is recorded in
    that stage's :class:`StageLog` and re-raised — the pipeline does not
    silently swallow errors, but it does guarantee every stage that *did*
    run gets logged before the exception propagates, so partial-run
    diagnostics are always available via the exception's
    ``__notes__``-style context (the caller can catch and still inspect
    ``pipeline.stage_logs`` collected so far).
    """

    def __init__(self, config: Optional[PreprocessingConfig] = None):
        self.config = config or load_preprocessing_config()
        self.stage_logs: List[StageLog] = []
        np.random.seed(self.config.random_seed)
        self._rng = np.random.default_rng(self.config.random_seed)

    def _run_stage(self, stage_name: str, config_used: Dict[str, Any], fn, *args, **kwargs):
        """Run a single stage, timing it and recording a StageLog."""
        start = time_module.perf_counter()
        warnings_before = list(logging.getLogger().handlers)  # no-op placeholder, real warnings captured per-stage below
        errors: List[str] = []
        try:
            result = fn(*args, **kwargs)
        except Exception as exc:
            elapsed = time_module.perf_counter() - start
            errors.append(str(exc))
            self.stage_logs.append(
                StageLog(
                    stage_name=stage_name,
                    execution_time_sec=elapsed,
                    n_samples=0,
                    warnings=[],
                    errors=errors,
                    config_used=config_used,
                )
            )
            logger.error("Stage '%s' failed after %.3fs: %s", stage_name, elapsed, exc)
            raise
        elapsed = time_module.perf_counter() - start
        logger.info("Stage '%s' completed in %.3fs.", stage_name, elapsed)
        return result, elapsed

    def run_from_source(
        self,
        data: Any,
        target_id: Optional[str] = None,
        mission: Optional[str] = None,
        time_col: Optional[str] = None,
        flux_col: Optional[str] = None,
        **run_kwargs,
    ) -> PipelineResult:
        """
        Run the pipeline directly on any Section-1 supported input type.

        This is a thin convenience wrapper around :func:`src.input_adapters.load_input`
        + :meth:`run` — it auto-detects and loads a lightkurve object, FITS
        file, CSV file, NumPy array pair, or pandas DataFrame, then runs
        the standard pipeline on the resulting ``(time, flux)`` arrays.

        Parameters
        ----------
        data:
            Any input type supported by :func:`src.input_adapters.load_input`.
        target_id, mission:
            Optional overrides. If omitted, values extracted from the
            source itself (e.g. a FITS header or lightkurve object) are
            used when available, falling back to ``"unknown"``.
        time_col, flux_col:
            Passed through to :func:`src.input_adapters.load_input` for
            CSV/DataFrame input with non-standard column names.
        **run_kwargs:
            Forwarded to :meth:`run` (``apply_augmentation``,
            ``save_output``, ``output_dir``).

        Returns
        -------
        PipelineResult
            Same as :meth:`run`.
        """
        from src.input_adapters import load_input

        time, flux, source_metadata = load_input(data, time_col=time_col, flux_col=flux_col)

        resolved_target_id = target_id or source_metadata.get("target_id") or "unknown"
        resolved_mission = mission or source_metadata.get("mission") or "unknown"

        logger.info(
            "run_from_source: loaded via '%s' adapter -> target_id='%s', mission='%s'.",
            source_metadata.get("source_type"), resolved_target_id, resolved_mission,
        )

        return self.run(
            time, flux,
            target_id=str(resolved_target_id),
            mission=str(resolved_mission),
            **run_kwargs,
        )

    def run(
        self,
        time: np.ndarray,
        flux: np.ndarray,
        target_id: str = "unknown",
        mission: str = "unknown",
        apply_augmentation: bool = False,
        save_output: bool = True,
        output_dir: Optional[str] = None,
    ) -> PipelineResult:
        """
        Execute the full preprocessing pipeline on a raw light curve.

        Parameters
        ----------
        time, flux:
            Raw ``(time, flux)`` arrays.
        target_id, mission:
            Identifiers used for reporting, logging, and output paths.
        apply_augmentation:
            If ``True``, applies the configured augmentation stage
            (train-time only — see ``src.augmentation``). Defaults to
            ``False`` since augmentation is not appropriate for inference
            or for building a canonical processed dataset.
        save_output:
            If ``True`` (default), writes ``processed.csv``,
            ``statistics.json``, ``preprocessing_report.json``, and
            ``metadata.json`` to ``<processed_dir>/<target_id>/``
            (Section 12).
        output_dir:
            Override for the output directory. Defaults to
            ``<project_root>/<config.output.processed_dir>/<target_id>``.

        Returns
        -------
        PipelineResult
            The full result, including processed arrays, windows,
            validation report, statistics, and per-stage logs.
        """
        self.stage_logs = []
        cfg = self.config

        # --- Stage: Load Data (data is passed in; this stage exists so the
        #     initial sample count is logged consistently with other stages) ---
        (time, flux), elapsed = self._run_stage(
            "load_data", {}, lambda: (np.asarray(time, dtype=np.float64), np.asarray(flux, dtype=np.float64))
        )
        self.stage_logs.append(
            StageLog("load_data", elapsed, n_samples=len(flux), config_used={})
        )

        # --- Stage: Validate ---------------------------------------------------
        report, elapsed = self._run_stage(
            "validate", {}, validate_lightcurve, time, flux, target_id, mission
        )
        self.stage_logs.append(
            StageLog(
                "validate", elapsed, n_samples=report.n_observations,
                warnings=list(report.warnings), config_used={},
            )
        )

        # --- Stage: Handle Missing Values ---------------------------------------
        (flux_filled, n_interp), elapsed = self._run_stage(
            "handle_missing_values",
            {"strategy": cfg.missing_values.strategy},
            handle_missing_values, time, flux, cfg.missing_values.strategy,
        )
        self.stage_logs.append(
            StageLog(
                "handle_missing_values", elapsed, n_samples=len(flux_filled),
                config_used={"strategy": cfg.missing_values.strategy},
                warnings=[f"Interpolated {n_interp} value(s)."] if n_interp else [],
            )
        )

        # --- Stage: Remove Outliers ---------------------------------------------
        (time_clean, flux_clean, outlier_stats), elapsed = self._run_stage(
            "remove_outliers",
            {"method": cfg.outliers.method},
            remove_outliers, time, flux_filled, cfg.outliers.method,
            cfg.outliers.sigma_threshold, cfg.outliers.mad_threshold,
            cfg.outliers.percentile_lower, cfg.outliers.percentile_upper,
        )
        self.stage_logs.append(
            StageLog(
                "remove_outliers", elapsed, n_samples=len(flux_clean),
                config_used={"method": cfg.outliers.method},
                warnings=[f"Removed {outlier_stats.n_removed} outlier(s) "
                          f"({outlier_stats.pct_removed:.2f}%)."],
            )
        )

        # --- Stage: Normalize -----------------------------------------------------
        (flux_norm, norm_params), elapsed = self._run_stage(
            "normalize", {"method": cfg.normalization.method},
            normalize, flux_clean, cfg.normalization.method,
        )
        self.stage_logs.append(
            StageLog(
                "normalize", elapsed, n_samples=len(flux_norm),
                config_used={"method": cfg.normalization.method},
            )
        )

        # --- Stage: Detrend (optional) --------------------------------------------
        if cfg.detrending.enabled:
            (flux_final, trend), elapsed = self._run_stage(
                "detrend", {"method": cfg.detrending.method},
                detrend, flux_norm, cfg.detrending.method,
                cfg.detrending.polynomial_degree, cfg.detrending.savgol_window,
                cfg.detrending.savgol_polyorder, cfg.detrending.running_median_window,
            )
            self.stage_logs.append(
                StageLog(
                    "detrend", elapsed, n_samples=len(flux_final),
                    config_used={"method": cfg.detrending.method, "enabled": True},
                )
            )
        else:
            flux_final = flux_norm
            self.stage_logs.append(
                StageLog("detrend", 0.0, n_samples=len(flux_final),
                          config_used={"enabled": False})
            )
            logger.info("Stage 'detrend' skipped (disabled in config).")

        time_final = time_clean

        # --- Stage: Window Generation ------------------------------------------------
        (windows,), elapsed = self._run_stage(
            "window_generation",
            {"window_size": cfg.windowing.window_size, "overlap": cfg.windowing.overlap},
            lambda: (generate_windows(
                time_final, flux_final,
                window_size=cfg.windowing.window_size,
                overlap=cfg.windowing.overlap,
                padding_mode=cfg.windowing.padding_mode,
                extra_metadata={"target_id": target_id, "mission": mission},
            ),),
        )
        self.stage_logs.append(
            StageLog(
                "window_generation", elapsed, n_samples=len(windows),
                config_used={"window_size": cfg.windowing.window_size, "overlap": cfg.windowing.overlap},
            )
        )

        # --- Stage: Statistics --------------------------------------------------------
        stats, elapsed = self._run_stage(
            "statistics", {}, compute_statistics, time_final, flux_final
        )
        self.stage_logs.append(
            StageLog("statistics", elapsed, n_samples=stats.n_samples, config_used={})
        )

        # --- Stage: Optional Augmentation (train-time only) ---------------------------
        if apply_augmentation:
            (flux_final,), elapsed = self._run_stage(
                "augmentation", {"enabled": cfg.augmentation.enabled},
                lambda: (augment(flux_final, cfg.augmentation, training=True, rng=self._rng),),
            )
            self.stage_logs.append(
                StageLog(
                    "augmentation", elapsed, n_samples=len(flux_final),
                    config_used={"enabled": cfg.augmentation.enabled},
                )
            )
        else:
            self.stage_logs.append(
                StageLog("augmentation", 0.0, n_samples=len(flux_final),
                          config_used={"applied": False})
            )
            logger.info("Stage 'augmentation' skipped (apply_augmentation=False).")

        # --- Stage: Save Processed Data -------------------------------------------------
        resolved_output_dir = None
        if save_output:
            save_start = time_module.perf_counter()
            try:
                resolved_output_dir = self._save_output(
                    target_id, time_final, flux_final, windows, report,
                    outlier_stats, norm_params, stats, output_dir,
                    pending_save_stage_name="save_output",
                )
            except Exception as exc:
                elapsed = time_module.perf_counter() - save_start
                self.stage_logs.append(
                    StageLog("save_output", elapsed, n_samples=len(flux_final),
                              errors=[str(exc)], config_used={})
                )
                logger.error("Stage 'save_output' failed after %.3fs: %s", elapsed, exc)
                raise
            elapsed = time_module.perf_counter() - save_start
            self.stage_logs.append(
                StageLog("save_output", elapsed, n_samples=len(flux_final), config_used={})
            )
            logger.info("Stage 'save_output' completed in %.3fs.", elapsed)
        else:
            self.stage_logs.append(
                StageLog("save_output", 0.0, n_samples=len(flux_final),
                          config_used={"save_output": False})
            )
            logger.info("Stage 'save_output' skipped (save_output=False).")

        result = PipelineResult(
            target_id=target_id,
            mission=mission,
            time=time_final,
            flux=flux_final,
            windows=windows,
            validation_report=report,
            outlier_stats=outlier_stats,
            normalization_params=norm_params,
            statistics=stats,
            stage_logs=self.stage_logs,
            output_dir=resolved_output_dir,
        )

        total_time = sum(s.execution_time_sec for s in self.stage_logs)
        logger.info(
            "Pipeline complete for '%s': %d stages, %.3fs total, %d final samples.",
            target_id, len(self.stage_logs), total_time, len(flux_final),
        )

        return result

    def _save_output(
        self,
        target_id: str,
        time_final: np.ndarray,
        flux_final: np.ndarray,
        windows: List[Window],
        report: ValidationReport,
        outlier_stats: OutlierStats,
        norm_params: Dict[str, Any],
        stats: LightCurveStatistics,
        output_dir: Optional[str],
        pending_save_stage_name: Optional[str] = None,
    ) -> str:
        """
        Write processed.csv, statistics.json, preprocessing_report.json, metadata.json.

        Parameters
        ----------
        pending_save_stage_name:
            If given, a placeholder :class:`StageLog` for this save stage
            itself is included in the written ``preprocessing_report.json``
            (with a zero execution time, since the real timing is only
            known after this function returns and is appended to
            ``self.stage_logs`` by the caller). This keeps the on-disk
            report's stage list complete rather than missing its own
            final entry.
        """
        import pandas as pd

        if output_dir is None:
            base = self.config.output.processed_dir
            if not os.path.isabs(base):
                base = os.path.join(_PROJECT_ROOT, base)
            output_dir = os.path.join(base, target_id)

        os.makedirs(output_dir, exist_ok=True)

        df = pd.DataFrame({"time": time_final, "flux": flux_final})
        df.to_csv(os.path.join(output_dir, "processed.csv"), index=False)

        with open(os.path.join(output_dir, "statistics.json"), "w", encoding="utf-8") as fh:
            json.dump(stats.to_dict(), fh, indent=2)

        metadata = {
            "target_id": target_id,
            "mission": report.mission,
            "n_final_samples": int(len(flux_final)),
            "normalization_params": norm_params,
            "outlier_stats": outlier_stats.to_dict(),
        }
        with open(os.path.join(output_dir, "metadata.json"), "w", encoding="utf-8") as fh:
            json.dump(metadata, fh, indent=2)

        report_dict = {
            "target_id": target_id,
            "mission": report.mission,
            "validation": report.to_dict(),
            "outlier_stats": outlier_stats.to_dict(),
            "normalization_params": norm_params,
            "statistics": stats.to_dict(),
            "stages": [s.to_dict() for s in self.stage_logs] + (
                [StageLog(pending_save_stage_name, 0.0, n_samples=len(flux_final), config_used={}).to_dict()]
                if pending_save_stage_name else []
            ),
            "n_windows": len(windows) if windows is not None else 0,
        }
        with open(os.path.join(output_dir, "preprocessing_report.json"), "w", encoding="utf-8") as fh:
            json.dump(report_dict, fh, indent=2)

        if self.config.output.save_windows and windows:
            windows_dir = os.path.join(output_dir, "windows")
            os.makedirs(windows_dir, exist_ok=True)
            arrs = windows_to_arrays(windows)
            np.savez_compressed(
                os.path.join(windows_dir, "windows.npz"),
                flux=arrs["flux"], time=arrs["time"], window_ids=arrs["window_ids"],
            )

        logger.info("Saved processed output for '%s' to '%s'.", target_id, output_dir)
        return output_dir
